### ISSUE TITLE
Data download speed very slow

### ISSUE THREAD

**Issue by balag59** [AI4Bharat/NPTEL2020-Indian-English-Speech-Dataset#4]
Hi, Even though my internet speed is sufficiently fast, the download speed of the data splits seem to be very slow and well below the usual download speeds with my connection. Would it be possible to have an alternate link/mirror where I can download the data from much quicker? This would be very helpful! Thanks!

**Comment by GokulNC** [comment]
Hello, since the data size is very large (more than a TB), we are unable to provide any other mirrors currently due to cost issues.

All our dataset splits are hosted on Zenodo.
From the download URL itself, you can check the Zenodo record's URL, and try to find if there's any faster way to download the record from Zenodo ([like this](https://zenodo.org/record/3676567)).

For example, you can get the following record URL:
https://zenodo.org/record/4590121

From:
https://github.com/AI4Bharat/NPTEL2020-Indian-English-Speech-Dataset/blob/f55881e/download_scripts/download_train_data.sh#L1


Or you can try downloading multiple files at a time to see if you are able to use all your available bandwidth.
(Or use multiple machines to download)

Please do share your experience if you find a easier way.

**Comment by balag59** [comment]
Thank you for the prompt response! I did try searching on Zenodo and downloading from there directly and that seems to be a lot quicker(atleast at first glance). Will try this going forward and let you know about the experience. Thanks!
